#!bash
mvn clean verify sonar:sonar \
  -Dsonar.projectKey=Reader-Writer-Problem \
  -Dsonar.projectName='Reader-Writer Problem' \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.token=sqp_d800ebdee7adb7e403b2d7f57ca449868e8ad8c3

